### ISSUE TITLE
max initcode size exceeded: code size 73726 limit 49152 (supplied gas 15010499)

### ISSUE THREAD

**Issue by Spider-yuchen** [NodeDAO/NodeDAO-Protocol#70]
branch: main
forge version: forge 0.2.0 (249538f 2023-02-10T07:39:50.4112747Z)

i want deploy a contract by myself, run the command: 
`forge c  .\script\Deploy-v2-all.s.sol:GoerliDeployNewContractScript --libraries "src/utils/Array.sol:Array:0xd926D359e0D21A3a5510Dfef379606112d6DA688" --verify`
and it shows me this error:
`Error: 
(code: -32000, message: err: max initcode size exceeded: code size 73726 limit 49152 (supplied gas 15010499), data: None)`

**Comment by llifezou** [comment]
`forge c .\script\Deploy-v2-all.s.sol` is the deployment script contract, the script contract is likely to be larger than the maximum contract limit, please use `forge script` to try
